### ISSUE TITLE
[Bug] not working alongside v4 of Spoon 

### ISSUE THREAD

**Issue by tomdavies** [weareferal/craft-matrix-field-preview#100]
I've hit a bug when trying to get this plugin to work alongside of the (freshly released v4 of Spoon).

Specifically, Spoon adds a `.hidden` class to  the `div.buttons` that this plugin appends its "Content Previews" button to:

<img width="1378" alt="Screenshot 2022-10-11 at 12 04 35" src="https://user-images.githubusercontent.com/136308/195074210-e3407dac-81b4-4c23-8d87-e8b8a67ccb62.png">

Probably the easiest fix would be to detect if Spoon is installed and target the `div.buttons-spooned`  instead when injecting the Content Previews button

**Comment by timmyomahony** [comment]
Thanks @tomdavies thanks for reporting this. I'll check it out.

**Comment by timmyomahony** [comment]
Haha, thanks @tomdavies

**Comment by timmyomahony** [comment]
This should be fixed with the `4.0.6` release:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.6
