### ISSUE TITLE
After saving the page, the preview image next to the block titles disappears

### ISSUE THREAD

**Issue by martinmana** [weareferal/craft-matrix-field-preview#103]
The plugin works like a charm. 
I added all my blocks, from the preview modal. Stoked. This is beautiful.
But after I saved the page, all the preview hover squares disappeared. 
If I add a new block, it will show display on it. But after saving, it will disappear as well. 

https://user-images.githubusercontent.com/49624628/221962424-1883fdca-e1a7-485d-b51d-c3fa126e4b8f.mp4

Could you please tell me if there´s something I can do to fix this??
Thanks. Kind regards.

**Comment by timmyomahony** [comment]
Sorry for the delay, I'll be looking into this ASAP.

**Comment by timmyomahony** [comment]
This should be fixed with the `4.0.6` release 👍🏻:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.6
