### ISSUE TITLE
Missing "Add block above" buttons

### ISSUE THREAD

**Issue by superflausch** [weareferal/craft-matrix-field-preview#104]
When triggering the "Add block above" action within the context menu of an existing block (see screenshot) no "Matrix Field Preview" buttons is shown.

In the DOM there are the Neo block buttons present and hidden by the "Matrix Field Preview" plugin, as expected. But there is no "Add block" button added by the plugin.

![Screenshot 2023-03-15 at 11 18 55](https://user-images.githubusercontent.com/539103/225280747-ba69ee62-1373-4fb9-88f4-65f33e82c50c.png)

No JS errors on the page. Using the latest Craft Pro 4.2.2, Matrix Field Preview 4.0.5 and Neo 3.7.1.

**Comment by timmyomahony** [comment]
Thanks for the report, there's definitely some weird stuff going on with the plugin in the more recent Craft versions. Will be looking at it and releasing a fix soon.

**Comment by superflausch** [comment]
Just a quick update. This is still an issue for us on CraftCMS 4.4.9 Pro, Neo 3.7.7 and Matrix Preview 4.0.5. Hope you can take a look at this soon. Cheers.

**Comment by timmyomahony** [comment]
This should be fixed with the `4.0.6` release 👍🏻:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.6
