### ISSUE TITLE
Setting the preview image location to a Servd filesystem crops images poorly

### ISSUE THREAD

**Issue by jpcarpenter** [weareferal/craft-matrix-field-preview#105]
I've come across an issue with preview images appearing "squished" on a filesystem using the [Servd](https://servd.host/) platform. It seems as though the plugin is cropping the uploaded preview images width to 800px, but the height stays the same as the original images height. This only appears to happen when using a Servd filesystem as the preview image location. Using Craft 4.4.11, Matrix Field Preview 4.0.5 and Neo 3.7.7.

(I have filed a ticket with Servd, but since I don't really know whose side this falls on, I figured I'd submit an issue here as well.)

Here is a screenshot of the image being uploaded:
<img width="780" alt="Screen Shot 2023-05-20 at 11 08 27 PM" src="https://github.com/weareferal/craft-matrix-field-preview/assets/5934150/f1db13f3-fc5b-422b-a3ce-c9f760ec69b6">

And here is what is being rendered within the modal:
<img width="617" alt="Screen Shot 2023-05-20 at 11 09 03 PM" src="https://github.com/weareferal/craft-matrix-field-preview/assets/5934150/cfbbe073-e7b0-45e1-8661-fe7884164faf">

**Comment by timmyomahony** [comment]
I added a small change to how the preview images are generated, moving from "stretch" to "fit" for the underlying Craft image transform. That should hopefully address the issue if it's on "our" side as opposed to Servd. Should be a part of release `4.0.6`:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.6
