### ISSUE TITLE
Preview images not showing

### ISSUE THREAD

**Issue by Devweb414** [weareferal/craft-matrix-field-preview#107]
I have set up custom images as a preview but once using the field in entries, only the default image shows. The plugin is not using the defined image as a preview.

https://prnt.sc/86dA6qg7Ablr
https://prnt.sc/lSp-q2g4AT-r

**Comment by timmyomahony** [comment]
Hi @Devweb414 what version of Craft are you running? Are you seeing any errors in the developer console when loading the entry with the matrix field?

**Comment by Devweb414** [comment]
Craft CMS Pro 4.4.17 And Plugin version 4.0.5.
There is no error in console. https://prnt.sc/1czOA_5FwJDl

**Comment by Devweb414** [comment]
Thanks for replying @timmyomahony 

I am using Craft CMS Pro 4.4.17 And Plugin version 4.0.5.
There is no error in the console. https://prnt.sc/1czOA_5FwJDl
