### ISSUE TITLE
Static translations not respected

### ISSUE THREAD

**Issue by turnstylerj** [weareferal/craft-matrix-field-preview#110]
## Description

When using a static translation in the structure the [Craft documentation](https://craftcms.com/docs/4.x/sites.html#provide-the-translations) calls for, overriding the text of the "Add Block" button doesn't apply.

### Configuration

`translations/en/matrix-field-preview.php`
```
<?php

return [
	'Add Block' => 'Add Module',
];
```

### Result
![2023-09-21 at 13 26 11](https://github.com/weareferal/craft-matrix-field-preview/assets/42223501/9ecd7e9a-f49c-4ecf-9312-55a76da4cb06)

### Expected Result
![2023-09-21 at 13 27 08](https://github.com/weareferal/craft-matrix-field-preview/assets/42223501/da607c74-097a-4d43-b138-318bc789cb52)

## Details
Craft version: Craft Pro 4.5.5
PHP version: 8.2.8
Matrix Field Preview version: 4.0.6

**Comment by timmyomahony** [comment]
Thanks @turnstylerj. The plugin is not currently configured for translations, as the frontend interface is set up using Javascript instead of being rendered by the server (due to the restrictions on what plugins can change in Craft).

That said, we should be able to to work around that and include translations.

**Comment by timmyomahony** [comment]
This should be address in [release `4.1.0`](https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.1.0). I've done a bit sweep of the code base to make as many strings translatable as possible, including the ones you were attempting to update. You can see the full list here:

https://github.com/weareferal/craft-matrix-field-preview/blob/main/src/translations/en/matrix-field-preview.php

Hopefully that helps. Try out the release and let me know how you get on.

**Comment by turnstylerj** [comment]
Works great, thanks!
