### ISSUE TITLE
Matrix "New Entry" Label Setting Not Being Respected

### ISSUE THREAD

**Issue by chadcrowell** [weareferal/craft-matrix-field-preview#131]
Craft 5...

My Matrix field setting for the "New Entry" label is set to "New Block" as shown [here](https://share.zight.com/Z4u90nyk).

Yet my entry edit page says "New Entry" as shown [here](https://share.zight.com/QwuJp896).

The plugin should respect this setting.

**Comment by timmyomahony** [comment]
I think this might be a bug. The plugin uses translation strings as of version 4.1.0:

https://github.com/timmyomahony/craft-matrix-field-preview/releases/tag/4.1.0

I have a feeling that the input you are using is now redundant and needs to be removed. In the meantime, could you try update the block text via a translation file? 

That would involve creating a translation file `translations/en/matrix-field-preview.php` and adding:

```
<?php

return [
	"New Entry" => "New Block",
];
```

**Comment by chadcrowell** [comment]
That did the trick, thanks Tim.

**Comment by timmyomahony** [comment]
Thanks @chadcrowell  I'll remove that settings field to avoid confusion in the future
