### ISSUE TITLE
[FR] Support Neo field as well

### ISSUE THREAD

**Issue by mediabeastnz** [weareferal/craft-matrix-field-preview#17]
We use the Neo field to build our sections and this plugin would be perfect for a lot of our sites.

Would support for Neo be hard? Happy to help out if you point me in the right direction ✌️

**Comment by timmyomahony** [comment]
Oooo. I think it would be possible. At the moment we use our own database table to track the previews. That table has a FK to the Craft matrix field block type. No reason why we could add another colum to track neo fields (assuming neo uses a totally different field to the matrix field - I haven't used it before).

**Comment by timmyomahony** [comment]
Just had a look at their source and seems they have their own tables so we could certainly track those as well as the matrix fields. It would require probably handling it under a separate tab or something. I will look into it a bit more. Thanks for the feedback.

**Comment by bryantAXS** [comment]
This is exactly what I've been looking for and needing with Neo! All our sites use this setup and we've been dying for something like this.

**Comment by timmyomahony** [comment]
Thanks @bryantAXS, sounds like it would be a good feature to work on so

**Comment by tyler-deboer** [comment]
+1 to that. Having Neo integration would be amazing.

**Comment by paragonn** [comment]
+2 to that. This would really great!

**Comment by timmyomahony** [comment]
Neo time! I've just released a new version 1.2.0 that adds basic Neo field support. Now you can add previews for both your regular matrix field inputs as well as neo fields.
