### ISSUE TITLE
Simplify configuration  across environments

### ISSUE THREAD

**Issue by timmyomahony** [weareferal/craft-matrix-field-preview#18]
The plugin uses the settings page to configure fields. This is by design as the preview fields are really a "once-off" configuration step, not something that should be done regularly (or be visible to end users). For the plugin to work we use a custom database table as well as the Craft assets to save images. 

Usually, on staging/production you would hide the settings page from users.  But this means it will be difficult to configure the plugin from staging/production. You can either

1) Enable settings temporarily on production and configure the plugin there
2) Configure the plugin locally then do a database dump/restore as well as copying over assets from one instance to another

We've got another plugin [`craft-remote-sync`](https://github.com/weareferal/craft-remote-sync) to help with approach 2

We could potentially create an import/export approach, but this would be a big feature. For the moment, approach 1 or 2 will have to suffice

**Comment by timmyomahony** [comment]
We're a step closer to configuration on staging/production with 1.2.0 as the settings pages can now be accessed independently of the settings section (which isn't accessible when `allowAdmin` = false). We don't want to add a menu item like other plugins though as you should really only access these matrix field settings now and again

**Comment by timmyomahony** [comment]
Closing for now, as this doesn't seem to be an issue for most users. Please comment if having to configure while admin is off on production/staging sites is a pain.

**Comment by timmyomahony** [comment]
Do you mean accessing it directly from a URL? Is the use case here accessing it on production, when the settings are hidden and `allowAdminChanges` is false?

**Comment by DTesch-Reem** [comment]
> Do you mean accessing it directly from a URL? Is the use case here accessing it on production, when the settings are hidden and `allowAdminChanges` is false?

Yes i am trying to access the plugin settings on a production environment, but it is not possible, because of this error message: "Unauthorized
Administrative changes are disallowed in this environment."
