### ISSUE TITLE
Ability to enable/disable preview on particular matrix fields

### ISSUE THREAD

**Issue by timmyomahony** [weareferal/craft-matrix-field-preview#31]
Currently it's all or nothing. We could add the ability to enable/disable on a per-matrix field basis. Alternatively, if we change the current approach to compliment the regular dropdown menu (https://github.com/weareferal/craft-matrix-field-preview/issues/19) then it might not be required to enable/disable

**Comment by VincentVanDenBossche** [comment]
Would love to see this enhancement!

**Comment by petehjfd** [comment]
Definite upvote for this.  It's not all that usable the way it is.

**Comment by timmyomahony** [comment]
Thanks for the feedback, will work on implementing this

**Comment by timmyomahony** [comment]
Just released version 1.1.0 which introduces this feature. You can now enable/disable previews on particular matrix fields as well as opt to "takeover" the default matrix field experience or just augment it

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/1.1.0
