### ISSUE TITLE
Disable the "Add" button when limit is reached.

### ISSUE THREAD

**Issue by jassok** [weareferal/craft-matrix-field-preview#35]
Default craft behavior on a matrix is to disable the "Add" button if you set a max number of rows for a matrix. This plugin doesn't appear to check for that and allows a user to attempt to add a new row even if they've hit the limit.

**Comment by timmyomahony** [comment]
Good catch. I hadn't thought of that. I'll be adding a fix for this

**Comment by timmyomahony** [comment]
This should be fixed with 1.0.7 and https://github.com/weareferal/craft-matrix-field-preview/pull/42
