### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by billymedia** [weareferal/craft-matrix-field-preview#58]
Trying to update the plugin and i am getting this error:

```
Database Exception: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'af_matrixfieldpreview_blocktypes_config_siteId_fk': needed in a foreign key constraint
The SQL being executed was: ALTER TABLE af_matrixfieldpreview_blocktypes_config DROP COLUMN siteId

Migration: weareferal\matrixfieldpreview\migrations\m201031_132510_remove_unused_site_id
```

Craftcms: 3.5.15.1
Plugin: 1.2.1
Mysql: 5.7.32
PHP: 7.3

**Comment by timmyomahony** [comment]
Just looking at this now

**Comment by timmyomahony** [comment]
@billymedia I've added a fix that hopefully sorts this issue. Please download version 1.2.3 and try migrate again. Let me know if it works OK. Apologies, I know how frustrating migration issues are on install

**Comment by billymedia** [comment]
@timmyomahony  i wasnt expecting you to resolve it so quick. I ended up commenting out the migration as craft was stuck in trying to complete the database upgrade, and i could no longer get into the backend, i'll give it a go and report back.

**Comment by billymedia** [comment]
Update worked fine. Thanks!

**Comment by timmyomahony** [comment]
Great, glad it's working 👍
