### ISSUE TITLE
Preview images not displaying in Matrix field within Neo

### ISSUE THREAD

**Issue by leightonhughes** [weareferal/craft-matrix-field-preview#65]
Hi there, I have a Matrix field used within a Neo field but the matrix field previews don't seem to be displaying. Any way to add this in an upcoming update?
I would ideally just use neo but this is an existing project and I'm reusing a matrix builder.

**Comment by timmyomahony** [comment]
Apologies for the delay in replying to your issue. I'm not sure why it was missed, no real excuse. Anyway, Neo should be supported for the plugin. I'm currently working on an update for the plugin, so hopefully that might address any issues you were having.

**Comment by timmyomahony** [comment]
Hopefully this will be fixed in the latest 3.0.0 release. See #73 for more. 

I'm going to close this issue for the moment, but if you run into it again please leave a comment and I'll re-open and investigate.
