### ISSUE TITLE
Craft 4.0 support

### ISSUE THREAD

**Issue by daltonrooney** [weareferal/craft-matrix-field-preview#66]
Leaving this here in case 4.0 compatibility is on the roadmap. We're currently testing on a forked repo and will report back if we have any issues.

**Comment by timmyomahony** [comment]
As mentioned in another issue/PR, I'm making a big update for the plugin, so I'll be testing 4.0 and adding support

**Comment by timmyomahony** [comment]
OK, I've pushed a new version 4.0.0 🥳 https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.0
