### ISSUE TITLE
As of 3.0.0 the Settings-Page cannot be accessed independently anymore.

### ISSUE THREAD

**Issue by DTesch-Reem** [weareferal/craft-matrix-field-preview#75]
As of 3.0.0 the Settings-Page cannot be accessed independently anymore.
Configuring while admin is off on production/staging sites is not ideal, please consider adding a menu button.

_Originally posted by @DTesch-Reem in https://github.com/weareferal/craft-matrix-field-preview/issues/18#issuecomment-1150870886_

**Comment by timmyomahony** [comment]
Do you mean accessing it directly from a URL? Is the use case here accessing it on production, when the settings are hidden and `allowAdminChanges` is false?

**Comment by DTesch-Reem** [comment]
> Do you mean accessing it directly from a URL? Is the use case here accessing it on production, when the settings are hidden and `allowAdminChanges` is false?

Yes i am trying to access the plugin settings on a production environment, but it is not possible, because of this error message: "Unauthorized
Administrative changes are disallowed in this environment."

**Comment by timmyomahony** [comment]
I've just pushed a change to version `3.0.1` that should ease the permissions so that you can access directly via `/admin/matrix-field-preview/` in the control panel.

**Comment by DTesch-Reem** [comment]
> I've just pushed a change to version `3.0.1` that should ease the permissions so that you can access directly via `/admin/matrix-field-preview/` in the control panel.

Wow you are fast! Thanks this work :)
In a future Update, will it be possible to access the Settings-Tab through a Menu-Button?

**Comment by timmyomahony** [comment]
Haha, no problem.  Adding it to the menu is a possibility. Would you expect to see it here?

![CleanShot 2022-06-09 at 10 35 39@2x](https://user-images.githubusercontent.com/615149/172816434-1e63bd08-6868-4951-aec1-406a908416bc.png)

An issue with this is that it would be visible to content creators/editors/publishers too. The plugin settings page is really only a configuration-step that should be done occasionally. In other words, it's not something the end-user (who is adding content) should see or access easily. 

Another option is to create a link in the "Utilities" section:

![CleanShot 2022-06-09 at 10 37 52@2x](https://user-images.githubusercontent.com/615149/172816873-e94d0036-ed68-4685-8247-4dd13783e56c.png)

This would make it accessible via the control panel on production, while not making it particularly obvious to the end user.
