### ISSUE TITLE
Craft v4 compatibility

### ISSUE THREAD

**Issue by bkrsmanovic** [weareferal/craft-matrix-field-preview#81]
Hello.

Great plugin. Is it possible that you make it compatible with v4 of Craft?

![image](https://user-images.githubusercontent.com/15169280/173438071-c43d2755-3972-40df-995d-36e060a5c43c.png)

**Comment by timmyomahony** [comment]
Good timing! I've just pushed a new version 4.0.0 with Craft 4 compatibility this evening:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.0
