### ISSUE TITLE
Non-takeover "Content Previews" button overlaps existing buttons

### ISSUE THREAD

**Issue by turnstylerj** [weareferal/craft-matrix-field-preview#84]
# Description

When using non-takeover display for either Matrix of Neo fields, the button containing the text "Content Previews" overlaps existing buttons.
![Screen Shot 2022-06-22 at 4 01 38 PM](https://user-images.githubusercontent.com/42223501/175169005-755ae767-00f8-4011-84f0-ec1cd2e3f26e.png)

## Additional Information
Craft CMS: v4.0.5.1
Neo: v3.1.1
Matrix Field Preview: v4.0.2

**Comment by timmyomahony** [comment]
Hi @turnstylerj  I haven't been able to come up with a great way of handling this, but you can now "takeover" the Neo field button altogether. This means that for Neo fields with many child blocks (that would normally suffer the issue you noted) you can just replace it with a single "Add Block" button.

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.5

I'm not sure if there's a better fix here? I could possible have the button drop down below the Neo button, but this might look a bit strange?

**Comment by turnstylerj** [comment]
Works for me! I was planning to use the takeover option anyway, so I'll go ahead and close this and if it really bothers someone else, they can resurrect it. 😄
