### ISSUE TITLE
Takeover option not available for Neo fields

### ISSUE THREAD

**Issue by turnstylerj** [weareferal/craft-matrix-field-preview#85]
# Description
Under "Configure Fields" for Neo fields, the "Takeover" display option is not available. This is available for Matrix fields.
![Screen Shot 2022-06-22 at 4 01 55 PM](https://user-images.githubusercontent.com/42223501/175169610-806c6710-11dc-4fe2-8237-96c030bcb0ca.png)

## Additional Information
Craft CMS: v4.0.5.1
Neo: v3.1.1
Matrix Field Preview: v4.0.2

**Comment by timmyomahony** [comment]
I think I may have consciously avoided taking over the Neo field so as not to interfere with it too much. I'll see what's involved in adding it as an option though.

**Comment by timmyomahony** [comment]
Hi @turnstylerj this should be added in the latest release 4.0.5

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.5

You can now take over the Neo button. This might address your other [#issue](https://github.com/weareferal/craft-matrix-field-preview/issues/84)
