### ISSUE TITLE
Neo field non-top level field & 'content preview' button on neo blocks with child nested blocks. 

### ISSUE THREAD

**Issue by deanfields** [weareferal/craft-matrix-field-preview#87]
I am able to select and add a non-top level block to the top-level. It would be awesome to have a content previews button for child blocks nested under top-level ones.

**Comment by robinsm** [comment]
Further to this, it would be great if we could hide non-top level blocks entirely to prevent them being added to an entry outside of the parent Neo block.

**Comment by janreges** [comment]
+1

We have a lot of nested non-top level blocks and it will be great to have an option how to hide them.

Our remporary workaround - we created preview 2 categories "TOP level components" and "Nested components - don't use it directly". Our editors are instructed to use only TOP level components.

**Comment by timmyomahony** [comment]
Hi folks, so just so I'm clear, Neo has two concepts at play here:

1. The ability to mark a block in a Neo field as "top level"
2. The ability to add "children" to Neo blocks (allowing for nesting).

The point of these two features together is that some blocks you _only_ ever want to nest, you don't ever want them to appear initially when the Neo field renders as top-level blocks.

Therefore there are two issue with this plugin:

1. The modal content preview is not respecting the "top level" setting. When the Neo field initially loads, it's possible to select a not-top-level block in the modal preview. The "top level" modal preview should only show "top level" neo blocks.
2. The plugin doesn't work at all for _child_ Neo blocks. Ideally, when a new Neo block is created - and it is configured to allow children - we should render the "content preview" button for those children.

**Comment by timmyomahony** [comment]
BTW, I'm going to review and pull in the PR that addresses this, I just want to make sure I understand the use case and can replicate the issues first.

**Comment by timmyomahony** [comment]
OK, the Neo field behavior has been updated in the latest release 4.0.5 which should tidy up some of the bugs.

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.5

Essentially any preview modal you open now on a Neo block should only display those previews that are relevant. For example if you click the top-level cotent preview button, the modal will only display those blocks that are level = 0. If you add a block that has child blocks available, the modal will open with only those child blocks.

This should avoid the issues reported here. Let me know how it goes and whether everything works OK.
