### ISSUE TITLE
Missing Inline Previews

### ISSUE THREAD

**Issue by robinsm** [weareferal/craft-matrix-field-preview#92]
Not all inline previews are being presented in Neo blocks when creating/editing entries. In some instances, the inline preview is presented in a specific block but if the same block is added again / appears a 2nd time, the inline preview may not show.

We can see the same console error reported in #88 so it may well be related.

Neo Blocks
Craft Pro 4.2.1.1
Matrix Field Preview 4.0.2

**Comment by timmyomahony** [comment]
Thanks @robinsm, could you provide a bit of detail on how your Neo field is configured? Are there multiple Neo fields on the entry you are trying to edit? Are there other matrix fields on the entry? Do you have top-level and non-top-level Neo fields? Even a screenshot of the field in the admin control panel would help.

I ask as I'm having a bit of trouble replicating the issue on my end.

**Comment by timmyomahony** [comment]
Hi @robinsm this should be fixed in the latest release 4.0.5

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.5

Now, inline preview images should appear on all Neo child blocks that are configured.
