### ISSUE TITLE
Block order not saving

### ISSUE THREAD

**Issue by daltonrooney** [weareferal/craft-matrix-field-preview#94]
When I re-order a block, I get a confirmation that the order was updated, but when I refresh the page the original order is restored. I can see that the sort order is being reflected in the database however.

https://capture.dropbox.com/lzWGsyZii0YXtjae

**Comment by timmyomahony** [comment]
Thanks @daltonrooney. This was also reported in #93. I've just created a new minor release 4.0.3 which should address this:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.3
