### ISSUE TITLE
Extra inline preview added to Super Table field when child of Matrix block

### ISSUE THREAD

**Issue by daltonrooney** [weareferal/craft-matrix-field-preview#96]
I've got a matrix field and some of the blocks include super table fields. If we select the "Matrix" layout for our Super Table field, the inline preview is appended to the child Super Table as well. Hopefully this screenshot can illustrate the problem. 

<img width="886" alt="Screen Shot 2022-09-08 at 10 23 57 AM" src="https://user-images.githubusercontent.com/742045/189187530-bfe9a9be-7fbf-440c-8126-88192e61fa00.png">

**Comment by timmyomahony** [comment]
Hey @daltonrooney ah, so the previews are incorrectly being included in any child SuperTable fields, when they shouldn't be?

**Comment by daltonrooney** [comment]
Right 👍🏻 I think it’s only when we use the “Matrix” Super Table field layout.

**Comment by timmyomahony** [comment]
@daltonrooney this should be fixed in the latest release 4.0.5 

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.5

Let me know if that clears up the issue for you or if you notice any other issues.
